<?php
namespace App\Permissions;

use App\Permissions\Traits\EnumEnhancements;

enum Dashboard: string
{
    use EnumEnhancements;

    case DASHBOARD_CAN_VIEW_TOTAL_SALES = 'DASHBOARD_CAN_VIEW_TOTAL_SALES';
    case DASHBOARD_CAN_VIEW_SALES_TREND = 'DASHBOARD_CAN_VIEW_SALES_TREND';
    case DASHBOARD_CAN_VIEW_NEW_ORDERS = 'DASHBOARD_CAN_VIEW_NEW_ORDERS';
    case DASHBOARD_CAN_VIEW_ORDERS_BY_STATUS = 'DASHBOARD_CAN_VIEW_ORDERS_BY_STATUS';
    case DASHBOARD_CAN_VIEW_ORDERS_BY_CHANNEL = 'DASHBOARD_CAN_VIEW_ORDERS_BY_CHANNEL';
}
