<?php
namespace App\Permissions;

use App\Permissions\Traits\EnumEnhancements;

enum Order: string
{
    use EnumEnhancements;

    case ORDER_CAN_VIEW = 'ORDER_CAN_VIEW';
    case ORDER_CAN_CREATE = 'ORDER_CAN_CREATE';
    case ORDER_CAN_UPDATE = 'ORDER_CAN_UPDATE';
    case ORDER_CAN_UPDATE_ONLY_MINE = 'ORDER_CAN_UPDATE_ONLY_MINE';
    case ORDER_CAN_DELETE = 'ORDER_CAN_DELETE';
    case ORDER_CAN_APPROVE = 'ORDER_CAN_APPROVE';
    case ORDER_CAN_VIEW_ALL_ORDERS = 'ORDER_CAN_VIEW_ALL_ORDERS';

    // Per-card visibility for the Orders-page stats widgets
    case ORDER_METRIC_VIEW_TOTAL_SALES = 'ORDER_METRIC_VIEW_TOTAL_SALES';
    case ORDER_METRIC_VIEW_NEW_ORDERS = 'ORDER_METRIC_VIEW_NEW_ORDERS';
    case ORDER_METRIC_VIEW_AVG_ORDER_VALUE = 'ORDER_METRIC_VIEW_AVG_ORDER_VALUE';
    case ORDER_METRIC_VIEW_AWAITING_PAYMENT = 'ORDER_METRIC_VIEW_AWAITING_PAYMENT';
    case ORDER_METRIC_VIEW_ORDERS_TO_SHIP = 'ORDER_METRIC_VIEW_ORDERS_TO_SHIP';
    case ORDER_METRIC_VIEW_SALES_TREND = 'ORDER_METRIC_VIEW_SALES_TREND';
    case ORDER_METRIC_VIEW_ORDERS_BY_STATUS = 'ORDER_METRIC_VIEW_ORDERS_BY_STATUS';
    case ORDER_METRIC_VIEW_ORDERS_BY_CHANNEL = 'ORDER_METRIC_VIEW_ORDERS_BY_CHANNEL';
    case ORDER_METRIC_VIEW_ORDERS_BY_PAYMENT_STATUS = 'ORDER_METRIC_VIEW_ORDERS_BY_PAYMENT_STATUS';
}
