<?php

namespace App\Permissions;

use App\Permissions\Traits\EnumEnhancements;

enum UserInformation: string
{
    use EnumEnhancements;

    case USERINFORMATION_CAN_VIEW = 'USERINFORMATION_CAN_VIEW';
    case USERINFORMATION_CAN_VIEW_CREDIT_CARD_INFO = 'USERINFORMATION_CAN_VIEW_CREDIT_CARD_INFO';
    case USERINFORMATION_CAN_VIEW_BILLING_ADDRESS = 'USERINFORMATION_CAN_VIEW_BILLING_ADDRESS';
    case USERINFORMATION_CAN_VIEW_SHIPPING_ADDRESS = 'USERINFORMATION_CAN_VIEW_SHIPPING_ADDRESS';
    case USERINFORMATION_CAN_ADD = 'USERINFORMATION_CAN_ADD';
    case USERINFORMATION_CAN_UPDATE = 'USERINFORMATION_CAN_UPDATE';
    case USERINFORMATION_CAN_DELETE = 'USERINFORMATION_CAN_DELETE';
    case USERINFORMATION_CAN_UPDATE_USER_STATUS = 'USERINFORMATION_CAN_UPDATE_USER_STATUS';
}
